import {Component,inject} from '@angular/core';import {ActivatedRoute,RouterLink} from '@angular/router';import {HttpClient} from '@angular/common/http';

@Component({standalone:true,imports:[RouterLink],template:`
<section class="page"><a routerLink="/" class="back">← Interview Prep</a><header><p class="label">SEPARATE SECTION</p><h1>Scenario-Based Interviews</h1><p>Here the question itself is a real engineering situation. Practise how you investigate, stabilise, diagnose, communicate and prevent recurrence.</p></header>
@for(x of items;track $index;let i=$index){<article><div class="num">{{(i+1).toString().padStart(2,'0')}}</div><div><span class="pill">{{x.type}}</span><h2>{{x.question}}</h2><section class="answer"><h3>How I would approach it</h3><p>{{x.answer}}</p></section><section class="example"><h3>Example reasoning</h3><p>{{x.example}}</p></section><section><h3>Interviewer follow-up</h3><p>{{x.followup}}</p></section></div></article>}</section>`,
styles:[`
:host{display:block;background:#f7f8fa;color:#1f2937}.page{max-width:1040px;margin:0 auto;padding:28px 34px 100px}.back{color:#64748b;text-decoration:none;font-size:13px}.label{margin:54px 0 11px;color:#2563eb;font-size:11px;font-weight:700;letter-spacing:.18em}header{border-bottom:1px solid #dfe4ea;padding-bottom:42px}h1{margin:0 0 14px;font-size:46px;letter-spacing:-.04em;color:#111827}header>p:last-child{max-width:850px;margin:0;color:#64748b;font-size:15px;line-height:1.85}article{display:grid;grid-template-columns:58px 1fr;gap:24px;padding:44px 0;border-bottom:1px solid #e2e6eb}.num{color:#94a3b8;font-size:13px;padding-top:7px}.pill{display:inline-block;color:#2563eb;background:#eff6ff;border:1px solid #dbeafe;border-radius:999px;padding:5px 9px;font-size:10px;text-transform:uppercase;letter-spacing:.12em}h2{font-size:27px;line-height:1.38;margin:12px 0 26px;color:#111827}section{margin:0 0 22px}h3{margin:0 0 8px;color:#475569;font-size:11px;letter-spacing:.12em;text-transform:uppercase}section p{margin:0;color:#475569;font-size:15px;line-height:1.85;max-width:850px}.answer{background:#fff;border:1px solid #dce4ed;border-left:4px solid #2563eb;border-radius:8px;padding:19px 21px}.example{background:#f1f5f9;border-radius:8px;padding:19px 21px}@media(max-width:700px){.page{padding:22px 18px 70px}h1{font-size:35px}article{grid-template-columns:30px 1fr;gap:10px}h2{font-size:23px}section p{font-size:14px}}
` ]})
export class PracticeComponent{private http=inject(HttpClient);items:any[]=[];constructor(route:ActivatedRoute){route.paramMap.subscribe(()=>this.load())}load(){this.http.get<any>('assets/data/practical-scenarios.json').subscribe(x=>this.items=x.questions.filter((q:any)=>q.type==='Scenario'))}}
