import {Component} from '@angular/core'; import {ActivatedRoute,RouterLink} from '@angular/router';
const banks:any={
csharp:{title:'C# / .NET',questions:[
['Simple','What are the four pillars of OOP?','Encapsulation hides state behind behavior, abstraction exposes only what callers need, inheritance reuses a base contract, and polymorphism lets the same contract have different implementations.','Example: an INotificationSender can have EmailSender and SmsSender implementations. The caller depends on the interface, not the concrete class.','Senior follow-up: When would you prefer composition over inheritance?'],
['Simple','What is the difference between IEnumerable and IQueryable?','IEnumerable executes LINQ against objects already in memory. IQueryable builds an expression that a provider such as EF Core can translate, commonly into SQL.','Example: filtering an IQueryable before ToList lets the database perform the filter instead of loading every row.','Senior follow-up: What problems can happen when client-side evaluation occurs?'],
['Medium','Explain async/await in C#.','async/await makes asynchronous operations easier to compose without blocking the calling thread while an awaited operation is incomplete. It does not automatically create a new thread.','Example: await httpClient.GetAsync(url) releases the request thread while I/O is pending.','Senior follow-up: Why is async void usually avoided outside event handlers?'],
['Medium','What is dependency injection and why use it?','A class receives its dependencies instead of constructing them itself. This reduces coupling, improves testing, and makes lifetime/configuration decisions centralized.','Example: OrderService receives IEmailSender through its constructor; tests can inject a fake sender.','Senior follow-up: Explain Singleton, Scoped and Transient lifetimes.'],
['Complex','How would you diagnose a high-CPU .NET API in production?','First establish scope and timing, inspect metrics and traces, correlate CPU with endpoints/deployments, capture appropriate runtime diagnostics, identify hot code paths, then reproduce and validate a fix.','Example: a LINQ operation repeatedly materializes a large collection inside a loop; profiling shows the allocation/CPU hotspot, then the query is moved outside the loop.','Senior follow-up: How would you distinguish CPU pressure from thread-pool starvation?'],
['Complex','Explain thread safety and how you would build a safe in-memory cache.','Shared mutable state must be protected from races. A cache can use ConcurrentDictionary for atomic operations, immutable values where possible, expiration metadata, and careful handling of cache stampedes.','Example: GetOrAdd with Lazy<T> can ensure only one expensive initialization wins for a key.','Senior follow-up: What happens if the factory itself fails?']
]},
angular:{title:'Angular',questions:[
['Simple','What is a component in Angular?','A component owns a view and its behavior. It combines a TypeScript class, template, and metadata and should represent a focused UI responsibility.','Example: a UserListComponent renders users and delegates data access to a service.','Senior follow-up: How would you keep a large component maintainable?'],
['Simple','What is dependency injection in Angular?','Angular provides configured dependencies to consumers rather than requiring them to construct services directly.','Example: inject UserService into a component and let the service encapsulate HttpClient calls.','Senior follow-up: Explain provider scopes.'],
['Medium','What is change detection and what does OnPush change?','Change detection updates the view when Angular determines component state may have changed. OnPush narrows checks around input reference changes, events, signals and explicit marking, encouraging predictable immutable state.','Example: replacing an array reference after an update works naturally with OnPush; mutating the same array reference can leave the view stale.','Senior follow-up: How would you find an unexpectedly expensive render?'],
['Medium','Observable vs Promise?','A Promise represents one eventual result. An Observable represents a stream that can emit multiple values, can be composed with RxJS operators, and can be unsubscribed.','Example: HTTP is commonly one emission; a search box value stream can emit many values with debounceTime and switchMap.','Senior follow-up: Why is switchMap useful for typeahead?'],
['Complex','How would you design an Angular application for performance?','Use lazy routes, small feature boundaries, OnPush where appropriate, efficient list rendering, image/code optimization, sensible RxJS composition, caching, and measurement with browser profiling rather than premature optimization.','Example: lazy-load an admin area and use switchMap plus debounceTime for search instead of firing a request on every keystroke.','Senior follow-up: How would you detect memory leaks?'],
['Complex','How would you migrate a large AngularJS application to Angular?','First establish boundaries and tests, identify shared services/directives, migrate incrementally by feature, introduce Angular-compatible APIs, reduce framework coupling, and continuously validate behavior/performance.','Example: migrate one workflow from controller/$scope to a standalone Angular feature while keeping a stable API boundary to legacy code.','Senior follow-up: What would you migrate first and why?']
]},
javascript:{title:'JavaScript',questions:[
['Simple','What is the difference between var, let and const?','var is function-scoped and can be redeclared. let and const are block-scoped; const prevents reassignment of the binding, though referenced objects can still mutate.','Example: a const array can have items pushed, but the variable cannot point to another array.','Senior follow-up: Why does block scope reduce bugs?'],
['Simple','What is a closure?','A closure is a function together with access to variables from its lexical environment even after the outer function has returned.','Example: a createCounter function returns a function that retains a private count variable.','Senior follow-up: Where can closures accidentally retain memory?'],
['Medium','Explain the JavaScript event loop.','Synchronous work runs on the call stack. Async callbacks are queued; microtasks such as Promise continuations are processed before the next task/macrotask.','Example: Promise.then usually runs before a setTimeout callback scheduled for the same turn.','Senior follow-up: How can excessive microtasks hurt responsiveness?'],
['Medium','What is the difference between == and ===?','== allows coercion before comparison; === compares without coercing types. In production code, strict equality is generally easier to reason about.','Example: 0 == false is true, while 0 === false is false.','Senior follow-up: When might coercion be intentional?'],
['Complex','Explain debounce vs throttle.','Debounce waits until activity pauses before invoking; throttle limits invocation frequency during continuous activity.','Example: debounce search input, throttle scroll or resize handling.','Senior follow-up: What UX tradeoff does debounce introduce?'],
['Complex','How would you debug a memory leak in a long-running web app?','Reproduce growth, capture heap snapshots, compare retained objects, inspect event listeners/timers/subscriptions, identify retaining paths, fix ownership cleanup, and verify heap stabilization.','Example: a component registers a window listener but never removes it, retaining the component after navigation.','Senior follow-up: How would you prove the fix?']
]},
sql:{title:'SQL',questions:[
['Simple','What is the difference between WHERE and HAVING?','WHERE filters rows before grouping; HAVING filters groups after aggregation.','Example: WHERE filters orders from 2026, HAVING filters customers whose total order value exceeds a threshold.','Senior follow-up: Can HAVING be used without GROUP BY?'],
['Simple','What is an INNER JOIN?','It returns rows where the join condition matches on both sides.','Example: join Orders to Customers on CustomerId to return only orders with matching customers.','Senior follow-up: What changes with LEFT JOIN?'],
['Medium','What is an index and why can too many indexes hurt?','An index accelerates selected access patterns but consumes storage and adds work to inserts, updates and deletes.','Example: an index on Order(CustomerId, CreatedAt) can support customer history queries ordered by date.','Senior follow-up: How do you decide column order in a composite index?'],
['Medium','Explain transaction isolation levels.','Isolation controls how concurrent transactions observe each other’s changes, trading consistency guarantees against concurrency.','Example: Read Committed commonly prevents dirty reads while allowing certain concurrent changes between statements.','Senior follow-up: What is a deadlock and how do you reduce it?'],
['Complex','How would you troubleshoot a slow SQL query?','Capture the exact query and parameters, inspect execution plan, row estimates, indexes, scans/seeks, joins, blocking, statistics and data volume; change one factor and measure again.','Example: a non-sargable predicate prevents index use; rewriting it makes the predicate searchable and reduces scanned rows.','Senior follow-up: Why can an index sometimes make a query slower?'],
['Complex','When would you use a window function?','When you need calculations across related rows without collapsing them into one row per group.','Example: ROW_NUMBER() can select the latest order per customer while retaining order columns.','Senior follow-up: How does it differ from GROUP BY?']
]},
'system-design':{title:'System Design',questions:[
['Simple','What is horizontal scaling?','Adding more application instances instead of making one machine larger.','Example: place several stateless API instances behind a load balancer.','Senior follow-up: What state must move out of the instance?'],
['Simple','Why use caching?','Caching stores frequently reused data closer to consumers to reduce latency and backend load.','Example: cache product metadata with a short TTL.','Senior follow-up: What causes stale-cache problems?'],
['Medium','Explain idempotency in APIs.','An operation is idempotent when repeating the same request has the same intended effect as performing it once.','Example: a payment API accepts an idempotency key so a client retry does not create a second charge.','Senior follow-up: Where should the idempotency record live?'],
['Medium','When would you use a queue?','A queue decouples producers and consumers, absorbs bursts, and enables asynchronous processing.','Example: an API writes a notification job to a queue while workers send messages later.','Senior follow-up: How do you handle duplicate delivery?'],
['Complex','Design a highly available notification service.','Define requirements and delivery semantics, expose an API, persist notification intent, enqueue work, use scalable workers, provider adapters, retries with backoff, dead-letter handling, idempotency and observability.','Example: POST /notifications stores a notification ID and enqueues it; workers claim jobs and record provider outcomes.','Senior follow-up: What happens if the provider is down for an hour?'],
['Complex','How do you reason about CAP?','Under a network partition, a distributed system must trade between consistency and availability; partition tolerance is assumed when partitions are possible.','Example: a system may prefer consistent reads for account balances while accepting eventual consistency for analytics.','Senior follow-up: What consistency does each data path actually require?']
]},
ai:{title:'AI & Agentic AI',questions:[
['Simple','What is an LLM?','A large language model predicts tokens from context using patterns learned during training. It can generate useful language but does not guarantee factual correctness.','Example: an assistant can summarize a document supplied in its context.','Senior follow-up: Why does context quality matter?'],
['Simple','What are embeddings?','Embeddings represent content as vectors so semantic similarity can be measured mathematically.','Example: store document chunks as vectors and retrieve chunks similar to a user question.','Senior follow-up: How do chunk size and overlap affect retrieval?'],
['Medium','What is RAG?','Retrieval-Augmented Generation retrieves relevant external information and supplies it to the model before generation.','Example: retrieve policy documents from a vector store, then ask the LLM to answer only from retrieved context.','Senior follow-up: How do you evaluate retrieval quality separately from generation?'],
['Medium','What is tool/function calling?','The model selects a structured tool request; application code executes the tool and returns the result to the model.','Example: an agent calls a ticket-search API rather than inventing ticket details.','Senior follow-up: How do you authorize tool calls?'],
['Complex','How would you design an enterprise agentic workflow?','Define bounded tasks, use an orchestrator, typed tools, explicit state, retrieval where needed, guardrails, authorization, timeouts, retries, human approval for high-risk actions, evaluation and tracing.','Example: triage agent classifies an issue, retrieval agent gathers evidence, analysis agent proposes a fix, and a controlled action tool opens a pull request.','Senior follow-up: When should an agent stop and ask for human review?'],
['Complex','How do you reduce hallucinations?','Ground answers in trusted context, constrain outputs, validate structured results, use retrieval and tool calls, require citations where appropriate, and measure factual accuracy with evaluation sets.','Example: a support agent must quote the retrieved error evidence before proposing a root cause.','Senior follow-up: How do you detect a regression after changing the prompt?']
]},
production:{title:'Production Debugging',questions:[
['Simple','What is RCA?','Root cause analysis identifies the underlying cause of an incident rather than stopping at the visible symptom.','Example: an API timeout is a symptom; exhausted DB connections may be the root cause.','Senior follow-up: What prevention action follows the RCA?'],
['Simple','What information do you collect first during an incident?','Impact, affected users/services, start time, recent changes, error rates, latency, logs, traces and infrastructure signals.','Example: compare the first failing timestamp with deployment and dependency timelines.','Senior follow-up: Why avoid changing many things at once?'],
['Medium','An API suddenly becomes slow. What do you check?','Check latency percentiles, traffic, CPU/memory, thread pool, dependency latency, DB queries, locks, connection pools, recent deployments and traces.','Example: tracing shows the API is fast until a DB call; the DB plan reveals a scan after data growth.','Senior follow-up: What metric distinguishes a few slow requests from broad degradation?'],
['Medium','How do you investigate intermittent failures?','Correlate failures by request ID, host, region, dependency, input and time; compare successful and failed traces and look for patterns.','Example: only one application instance fails because its configuration differs after a partial deployment.','Senior follow-up: How would you safely validate the hypothesis?'],
['Complex','How do you handle a production deadlock?','Capture deadlock graphs/logs, identify transaction/resource order, reduce transaction scope, enforce consistent lock ordering and improve indexing where appropriate.','Example: two transactions update tables in opposite order; standardizing the order removes the cycle.','Senior follow-up: Why is simply retrying not always enough?'],
['Complex','A deployment caused errors. What is your approach?','Assess blast radius, stop further rollout, compare versions/configuration, rollback or mitigate safely, preserve evidence, communicate impact, then perform RCA and prevention work.','Example: a feature flag can disable the changed path while the team validates a rollback.','Senior follow-up: What should be included in the post-incident action items?']
]}};
@Component({standalone:true,imports:[RouterLink],template:`
<section class="practice"><a routerLink="/" class="back">← Dashboard</a><div class="head"><div><p class="label">QUESTION BANK</p><h2>{{topic.title}}</h2><p class="desc">Simple → Medium → Complex. Learn the answer, then explain the example and handle the senior follow-up.</p></div><div class="count">{{index+1}} / {{topic.questions.length}}</div></div>
<div class="filters"><button [class.on]="level==='All'" (click)="setLevel('All')">All</button><button [class.on]="level==='Simple'" (click)="setLevel('Simple')">Simple</button><button [class.on]="level==='Medium'" (click)="setLevel('Medium')">Medium</button><button [class.on]="level==='Complex'" (click)="setLevel('Complex')">Complex</button></div>
@if(current();as q){<article class="question"><div class="meta"><span>{{q[0]}}</span><span>30–60 sec first</span></div><h3>{{q[1]}}</h3><section><h4>Answer</h4><p>{{q[2]}}</p></section><section><h4>Clear example</h4><p>{{q[3]}}</p></section><section class="follow"><h4>Senior follow-up</h4><p>{{q[4]}}</p></section><div class="actions"><button (click)="prev()" [disabled]="index===0">← Previous</button><button (click)="next()">Next question →</button></div></article>}</section>`,styles:[`
.practice{max-width:980px;padding:30px 42px 70px}.back{color:#77869a;text-decoration:none;font-size:12px}.head{display:flex;justify-content:space-between;align-items:end;margin:32px 0 18px}.label{color:#7dd3fc;font-size:10px;letter-spacing:.18em}.head h2{font-size:40px;margin:5px 0}.desc{color:#7d8ba0;font-size:13px}.count{font:12px monospace;color:#65758b}.filters{display:flex;gap:7px;margin-bottom:13px}.filters button,.actions button{border:1px solid #263446;background:#0d141f;color:#8c9aad;border-radius:7px;padding:8px 12px;font-size:11px}.filters .on{background:#dff6ff;color:#09121a;border-color:#dff6ff}.question{border:1px solid #223044;background:#0c131d;border-radius:14px;padding:28px}.meta{display:flex;gap:8px}.meta span{font-size:10px;color:#7dd3fc;border:1px solid #263b52;padding:5px 8px;border-radius:99px}.question h3{font-size:24px;line-height:1.3;margin:20px 0 24px}.question section{border-top:1px solid #1b2635;padding:17px 0}.question h4{font-size:11px;letter-spacing:.12em;color:#7dd3fc;text-transform:uppercase;margin:0 0 8px}.question p{color:#b5c0cf;font-size:13px;line-height:1.7;margin:0}.follow{background:#101923;margin:10px -12px;padding-left:12px!important;padding-right:12px}.actions{display:flex;justify-content:space-between;margin-top:20px;border-top:1px solid #1b2635;padding-top:20px}.actions button:last-child{background:#dff6ff;color:#09121a;border-color:#dff6ff}@media(max-width:800px){.practice{padding:22px 18px}.head{align-items:start}.head h2{font-size:31px}.question{padding:20px}.question h3{font-size:20px}}` ]}) export class TopicComponent{topic:any={title:'',questions:[]};index=0;level='All';filtered:any[]=[];constructor(route:ActivatedRoute){route.paramMap.subscribe(p=>{const key=p.get('slug')||'csharp';this.topic=banks[key]||banks.csharp;this.index=0;this.apply()})}apply(){this.filtered=this.level==='All'?this.topic.questions:this.topic.questions.filter((q:any)=>q[0]===this.level);if(this.index>=this.filtered.length)this.index=0}setLevel(l:string){this.level=l;this.index=0;this.apply()}current(){return this.filtered[this.index]}next(){if(this.filtered.length)this.index=(this.index+1)%this.filtered.length}prev(){if(this.filtered.length)this.index=(this.index-1+this.filtered.length)%this.filtered.length}}